### ISSUE TITLE
[1.20.1] cannot join dedicated server

### ISSUE THREAD

**Issue by kuba26038** [Artienia80/RubinatedNether#10] opened 2024-09-22 17:51 UTC
![obraz](https://github.com/user-attachments/assets/efdc4c69-f687-401a-9f5c-2740cbf0e8f0)
whenever i try to join a server, i get this message. nothing informative appears in either the client's log or the server's, and it took me ages to figure out that it was caused by this mod
![obraz](https://github.com/user-attachments/assets/a5c69a15-0896-480b-9d20-f06ff2ba9498)
both the server and the client were using forge 47.3.10 for 1.20.1, and this is replicable when only this mod and architectury in the mods folder

**Comment by serenyadev** [comment] 2024-09-22 17:52
This doesn't seem to be caused by this mod, could you send the logs?

**Comment by kuba26038** [comment] 2024-09-22 18:30
https://pastebin.com/mHskPaP3
i fear it is caused by this mod, as when i removed it everything worked fine on my modpack. like i said, this still happens when it's just this mod and architectury installed

**Comment by serenyadev** [comment] 2024-09-22 18:32
could you send the client log too?

**Comment by kuba26038** [comment] 2024-09-22 18:42
server's debug.log: https://pastebin.com/ERNFLvYn

client's debug.log: 
[debug.log](https://github.com/user-attachments/files/17090832/debug.log)
client's latest.log: 
[latest.log](https://github.com/user-attachments/files/17090835/latest.log)

**Comment by serenyadev** [comment] 2024-09-22 18:48
hmm this is super weird, there's no error in any of the logs and this mod doesn't do any custom networking

**Comment by serenyadev** [comment] 2024-09-22 18:48
Im gonna test some stuff and see if i can figure out whats causing this

**Comment by Artienia80** [comment] 2024-09-23 13:00
Hello Kuba. I am Artienia, author of RN.
We are still actively working on your major bug report. We suspect it has to be related to architectuary so we are moving away. Expect the next update to resolve this matter.

Thank you for your patience .

**Comment by Artienia80** [comment] 2024-09-25 08:01
Fixed by Bodge in 1.1.1

**Closed** 2024-09-25 08:01 UTC
Labels: bug
